//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeWeb.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatAppointment
    {
        public long AppointmentID { get; set; }
        public Nullable<long> PatNum { get; set; }
        public Nullable<int> OperatoryID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsAllDay { get; set; }
        public string Description { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
