//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeWeb.DB
{
    using System;
    
    public partial class PatientDetail
    {
        public long PatNum { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public byte Gender { get; set; }
        public string Email { get; set; }
        public string HmPhone { get; set; }
        public string WkPhone { get; set; }
        public string GenderValue { get; set; }
    }
}
